# Site settings
title: Charleston Amateur Radio Society
email: mike@w4kwc.com
description: >-
  Welcome to the Charleston Amateur Radio Society.
  This club was established in 1971.
baseurl: "/wa4usn"
url: "https://charleston-amateur-radio-society.github.io"
callsign: WA4USN

# Build settings
markdown: kramdown
permalink: /posts/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
